version: 2
sources:
  - name: raw_data
    schema: '{{ var ("source_dataset_name") }}'
    tables:
      - name: _dlt_loads
      - name: workspaces
      - name: tags
      - name: teams
      - name: users
      - name: projects
      - name: tasks
      - name: stories
      - name: sections
      - name: workspaces__email_domains
      - name: users__workspaces
      - name: tasks__custom_fields
      - name: tasks__custom_fields__enum_options
      - name: tasks__followers
      - name: tasks__memberships
      - name: projects__custom_field_settings
      - name: projects__followers
      - name: projects__members
  - name: transformed_data
    schema: '{{ var ("destination_dataset_name") }}'
    tables:
      - name: dlt_processed_load_ids

models:
      - name: dlt_processed_load_ids
        description: "This table contains all processed load ids for incremental loading"
      - name: _dlt_loads
        description: "Created by DLT. Tracks completed loads"
        columns:
          - name: load_id
            tests:
              - not_null
          - name: schema_name
          - name: status
            tests:
              - not_null
          - name: inserted_at
            tests:
              - not_null
          - name: schema_version_hash
      - name: workspaces
        columns:
          - name: gid
          - name: is_organization
          - name: name
          - name: resource_type
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: tags
        columns:
          - name: gid
          - name: color
          - name: created_at
          - name: name
          - name: notes
          - name: permalink_url
          - name: resource_type
          - name: workspace__gid
          - name: workspace__resource_type
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: teams
        columns:
          - name: gid
          - name: description
          - name: name
          - name: organization__gid
          - name: organization__resource_type
          - name: permalink_url
          - name: resource_type
          - name: visibility
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: users
        columns:
          - name: gid
          - name: email
          - name: name
          - name: resource_type
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: projects
        columns:
          - name: gid
          - name: archived
          - name: color
          - name: completed
          - name: created_at
          - name: default_view
          - name: icon
          - name: modified_at
          - name: name
          - name: notes
          - name: owner__gid
          - name: owner__resource_type
          - name: permalink_url
          - name: public
          - name: resource_type
          - name: team__gid
          - name: team__resource_type
          - name: workspace__gid
          - name: workspace__resource_type
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: tasks
        columns:
          - name: gid
            tests:
              - not_null
          - name: assignee__gid
          - name: assignee__resource_type
          - name: assignee_status
          - name: completed
          - name: created_at
          - name: due_on
          - name: modified_at
          - name: name
          - name: notes
          - name: num_subtasks
          - name: permalink_url
          - name: resource_type
          - name: resource_subtype
          - name: workspace__gid
          - name: workspace__resource_type
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
          - name: start_on
      - name: stories
        columns:
          - name: gid
          - name: assignee__gid
          - name: assignee__resource_type
          - name: created_at
          - name: created_by__gid
          - name: created_by__resource_type
          - name: resource_type
          - name: source
          - name: text
          - name: type
          - name: resource_subtype
          - name: target__gid
          - name: target__resource_type
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
          - name: project__gid
          - name: project__resource_type
      - name: sections
        columns:
          - name: gid
          - name: created_at
          - name: name
          - name: project__gid
          - name: project__resource_type
          - name: resource_type
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: workspaces__email_domains
        columns:
          - name: value
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: users__workspaces
        columns:
          - name: gid
          - name: resource_type
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: tasks__custom_fields
        columns:
          - name: gid
          - name: enabled
          - name: enum_value__gid
          - name: enum_value__color
          - name: enum_value__enabled
          - name: enum_value__name
          - name: enum_value__resource_type
          - name: name
          - name: description
          - name: display_value
          - name: resource_subtype
          - name: resource_type
          - name: is_formula_field
          - name: is_value_read_only
          - name: type
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
          - name: created_by__gid
          - name: created_by__name
          - name: created_by__resource_type
      - name: tasks__custom_fields__enum_options
        columns:
          - name: gid
          - name: color
          - name: enabled
          - name: name
          - name: resource_type
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: tasks__followers
        columns:
          - name: gid
          - name: resource_type
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: tasks__memberships
        columns:
          - name: project__gid
          - name: project__name
          - name: section__gid
          - name: section__name
          - name: _dlt_root_id
            tests:
              - not_null
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: projects__custom_field_settings
        columns:
          - name: gid
          - name: resource_type
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: projects__followers
        columns:
          - name: gid
          - name: resource_type
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: projects__members
        columns:
          - name: gid
          - name: resource_type
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique